export const alignItems = ["normal",
"stretch",
"center",
"start",
"end",
"flex-start",
"flex-end",
"self-start",
"self-end",
"baseline",
"first baseline",
"last baseline", 
"safe center",
"unsafe center",
"inherit",
"initial",
"revert",
"revert-layer",
"unset",];

export const justifyContent = ["flex-start",
"flex-end",
"center",
"space-between",
"space-around",
"space-evenly",
"initial",
"inherit",];

export const textAlign = ["left",
"right",
"center",
"justify",
"initial",
"inherit",];